backend:
  name: vetnathana

local_backend: true
media_folder: static/assets
public_folder: /assets
locale: "pt"

collections:
  - name: consultation
    label: Atendimentos
    label_singular: Atendimento
    identifier_field: description
    description: Adicionar o registro de uma nova consulta
    folder: src/consultation
    create: true
    delete: false
    fields:
      - { name: description, label: Descricao, required: true, widget: "text" }
      - {
          name: image,
          label: Imagem,
          required: true,
          widget: "image",
          allow_multiple: false,
        }
